# Generated by Django 2.2 on 2019-04-30 02:10

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(max_length=100)),
                ('addressLine2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipCode', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardInfo_1', models.CharField(max_length=100)),
                ('cardInfo_2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', djongo.models.fields.ArrayModelField(model_container=models.ManyToManyField(to='Address'))),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=100)),
                ('business', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.CharField(max_length=100)),
                ('sellingPrice', models.CharField(max_length=100)),
                ('unlockPrice', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workfile', models.CharField(max_length=100)),
                ('cartQty', models.IntegerField()),
                ('items', djongo.models.fields.ArrayModelField(model_container=models.ManyToManyField(to='Items'))),
                ('payments', djongo.models.fields.ArrayModelField(model_container=models.ManyToManyField(to='Payment'))),
                ('customer', models.ManyToManyField(to='shoppingCart.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenderType', models.CharField(max_length=100)),
                ('tenderAmount', models.CharField(max_length=100)),
                ('cardType', models.CharField(max_length=100)),
                ('cardInfo', models.ManyToManyField(to='shoppingCart.CardInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemNumber', models.IntegerField()),
                ('vendorName', models.CharField(max_length=100)),
                ('modelNUmber', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.ManyToManyField(to='shoppingCart.Price')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=models.ManyToManyField(to='shoppingCart.Phone'),
        ),
    ]
