# Generated by Django 2.2 on 2019-05-01 17:05

from django.db import migrations, models
import djongo.models.fields
import shoppingCart.models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sCart', djongo.models.fields.EmbeddedModelField(model_container=shoppingCart.models.SCart, null=True)),
                ('headline', models.CharField(max_length=255)),
            ],
        ),
    ]
